### ISSUE TITLE
Windows pathing issue on dev / build

### ISSUE THREAD

**Issue by grbd** [nuxt-themes/docus#684]
Hi,
It looks as if there's an issue when running `yarn dev` or `yarn build` under windows
Seems to be some sort of pathing issue
```
√ Using Nuxt Typography v0.0.17                                                                                                                                 17:37:40
i Client built in 4227ms                                                                                                                                        17:37:51
i Building server...                                                                                                                                            17:37:51
√ Server built in 3795ms                                                                                                                                        17:37:55
√ Generated public .docs/.output/public                                                                                                                   nitro 17:37:55
i Initializing prerenderer                                                                                                                                nitro 17:37:55

 ERROR  Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

  at new NodeError (node:internal/errors:377:5)
  at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1076:11)
  at defaultResolve (node:internal/modules/esm/resolve:1156:3)
  at ESMLoader.resolve (node:internal/modules/esm/loader:605:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
  at link (node:internal/modules/esm/module_job:78:36)
```

I think it's related to the drive letter C: or D: in the path, although I've not been able to tie down exactly which bit of code is the problem.

It's the same issue mentioned here https://github.com/nuxt-themes/docus/issues/681 by [KyleRicardo](https://github.com/KyleRicardo)

someone else also mentioned it here - https://github.com/nuxt-themes/docus-starter/issues/7

**Comment by phenomen** [comment]
The same. I've tried npm and pnpm.
```
Nuxt 3.0.0 with Nitro 1.0.0
√ Using Nuxt Typography v0.0.17

  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.218:3000/

√ Nitro built in 1221 ms
i Vite client warmed up in 4596ms

 ERROR  [worker reload] [worker init] Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

  at new NodeError (node:internal/errors:393:5)
  at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:986:11)
  at defaultResolve (node:internal/modules/esm/resolve:1066:3)
  at nextResolve (node:internal/modules/esm/loader:161:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:831:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:413:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
  at link (node:internal/modules/esm/module_job:76:36)
```

**Comment by zoey-kaiser** [comment]
I will raise my comment from #681 here again. We had a similar issue with Windows reading URL schemas differently then Mac or Windows. If it helps you can see how we approached the fix here:

https://github.com/sidebase/nuxt-session/pull/13

**Comment by grbd** [comment]
In my case it's windows 10 21H2
Tried from both a vanilla command prompt and a visual studio 2022 developer command prompt (same as a regular one but with additional tools installed)

Based on the above comments I'm guessing there's a `import { resolve } from 'path'` in a dependency some place that needs replacing with a
```
import { createResolver } from '@nuxt/kit'
const { resolve } = createResolver(import.meta.url)
```
similar to what's already done in the nuxt.config.ts
although the stack trace I'm getting isn't giving me any clues as to where it is other than it happening after the prerenderer

**Comment by Tahul** [comment]
@grbd ; I've published this commit https://github.com/Tahul/pinceau/commit/5a8b4e92ef7ccbe27996765f3b8eaadb755b439d

I was using resolve from `path` and replaced it with [`pathe`](https://github.com/unjs/pathe).

This might help on this issue, could you try reinstalling all dependencies with fresh lockfile?

Not sure this will help but it is first step.

Thanks 🙏

**Comment by grbd** [comment]
I tried doing a fresh clone to avoid any cache's or lock files being an issue
```
git clone https://github.com/nuxt-themes/docus
cd docus
yarn install
```
Then a `yarn build` / `yarn dev` (which tries to build inside .docs) but the result is still the same error sorry
also I double checked the version of pinceau was 0.6.26 the one you've just updated

Error is still
```
 ERROR  [worker reload] [worker init] Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

  at new NodeError (node:internal/errors:377:5)
  at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1076:11)
  at defaultResolve (node:internal/modules/esm/resolve:1156:3)
  at ESMLoader.resolve (node:internal/modules/esm/loader:605:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
  at link (node:internal/modules/esm/module_job:78:36)
```

**Comment by Tahul** [comment]
I'm afraid we'll have to wait for me to have access to a Windows environment.

Thank you so much for the quick answer though.

I hope to fix this tomorrow, without being able to track which line throws this error I won't be able to fix this.

**Comment by MrSociety404** [comment]
Nuxt/i18n had the same issue recently https://github.com/nuxt-community/i18n-module/issues/1518 

They change the absolute path by a relative path with an assert type.

Hope it can help you

**Comment by grbd** [comment]
Just spotted a few places its showing up in the generated files under the .nuxt build directory

`docus\.docs\.nuxt\app.config.mjs`
```ts

import { defuFn } from 'C:/D/Temp/18/test3/docus/node_modules/defu/dist/defu.mjs'

const inlineConfig = {}

import cfg0 from "C:/D/Temp/18/test3/docus/.docs/app.config.ts"
import cfg1 from "C:/D/Temp/18/test3/docus/app.config.ts"
import cfg2 from "C:/D/Temp/18/test3/docus/node_modules/@nuxt-themes/typography/app.config.ts"

export default defuFn(cfg0, cfg1, cfg2, inlineConfig)
```

`docus\.docs\.nuxt\dev\index.mjs`
```ts
...
import _OxsnGi2RuD from 'C:/D/Temp/18/test3/docus/node_modules/pinceau/dist/nitro';
...
```

an entry within `docus\.docs\.nuxt\dist\server\server.mjs.map`





`docus\.docs\.nuxt\prerender\chunks\nitro-prerenderer.mjs`
```ts
...
import _OxsnGi2RuD from 'C:/D/Temp/18/test3/docus/node_modules/pinceau/dist/nitro';
...
```

**Comment by Tahul** [comment]
Hey @grbd ;

That is immensely helpful, I suggest there is some issues in path resolving upstream.

@danielroe ; I've only identified this line in Nitro that seem not to use `pathe`:
https://github.com/unjs/nitro/blob/ffcbdbb2c65e43da1e985f952a25859ab298a140/src/runtime/entries/nitro-dev.ts#L4

Any idea on what could be the source of this? I would happily work on a PR to solve it.

Here is some code pointers that might help on digging:

- Pinceau pushes Nitro plugin into `nitro.plugins`:
	- https://github.com/Tahul/pinceau/blob/e99c19bbca4ef4626c59d35bbd5bf652df6d2753/src/nuxt.ts#L44
- Nuxt load and merges configs:
	- 	https://github.com/nuxt/framework/blob/71fed589c14eed3ebde5e1ccfd40e49651a3b0c6/packages/kit/src/loader/config.ts#L9
- Nuxt writes the `app.config` template:
	- https://github.com/nuxt/framework/blob/71fed589c14eed3ebde5e1ccfd40e49651a3b0c6/packages/nuxt/src/core/templates.ts#L215

In the meantime I'm afraid I'll have to suggest running it in WSL.

**Comment by Rekryt** [comment]
After fix #686 at https://github.com/nuxt-themes/docus/blob/dev/app/module.ts#L5
only these broken pathes remain:
`import 'C:/Users/.../node_modules/pinceau/dist/nitro'`

**Comment by grbd** [comment]
So for the plugin line
https://github.com/Tahul/pinceau/blob/e99c19bbca4ef4626c59d35bbd5bf652df6d2753/src/nuxt.ts#L44

```ts
// I tried swapping
nuxt.options.nitro.plugins.push(modulePath.resolve('./nitro'))
// with an absolute path
nuxt.options.nitro.plugins.push('file:///C:/D/SourceCode/Forks/pinceau/dist/nitro')
```

However the path then ends up getting treated as a relative path and gets a bit mangled
` Cannot find module 'C:\D\Temp\18\.docs\server\file:\C:\D\SourceCode\Forks\pinceau\dist\nitro' imported from C:\D\Temp\18\test3\docus-orig\.docs\.nuxt\prerender\index.mjs`

So the next question is whereabouts it's getting parsed ether in nuxt or nitro

**Comment by grbd** [comment]
Update, commenting that one line that adds the pinceau nitro plugin
https://github.com/Tahul/pinceau/blob/e99c19bbca4ef4626c59d35bbd5bf652df6d2753/src/nuxt.ts#L44

Allows us to get some semblence of an output we can preview
```
# switched to pnpm to get everything to build and link together during debugging
pnpm build
pnpm preview
```
But dev just hangs (probably because we're missing the plugin)
```
pnpm dev
```

I think the issue is someplace within nitro, I finally managed to get the depends to build and link together so more digging required.

**Comment by Tahul** [comment]
@grbd ; are you saying the build passes with `pnpm build` and `pnpm preview` ?

**Comment by grbd** [comment]
> @grbd ; are you saying the build passes with `pnpm build` and `pnpm preview` but `dev` is broken ?

Only if that line is commented out which removes the nitro plugin but that's not really a fix just an observation
I think I've discovered one of the problems in nitro so I've added a pull request for that
although we also need to add the .mjs extension to the path below within pinceau
```
# This
nuxt.options.nitro.plugins.push(modulePath.resolve('./nitro'))
# instead needs to be something like this
nuxt.options.nitro.plugins.push(modulePath.resolve('./nitro.mjs'))
```

Not sure if there's a better way but overall it gets us a little bit further along

**Comment by florian-lefebvre** [comment]
I'm encountering the same issue using `pnpm dev` on Windows 11

**Comment by osmandlsmn** [comment]
i also encountered the same problem

**Comment by sdsoldi** [comment]
Same here with win10

**Comment by Tahul** [comment]
Hello @here !

Could you try regenerating your lockfiles to grab latest version of Pinceau, using Docus ^1.0.1?

I finally had access to a Windows dev environment and fixed it today!

**Comment by Rekryt** [comment]
@Tahul , yes, everything is fine, thank you!!👍

**Comment by florian-lefebvre** [comment]
Same here 👍

**Comment by grbd** [comment]
Very cool works like a charm checked build, dev, preview
I'll close the issue down now

**Comment by sdsoldi** [comment]
Working on win10. thank you!! 👏

**Comment by Tahul** [comment]
So happy it fixed it for all of you, have fun documenting! 🙂
